[workspace]
members = ["server", "client", "shared"]
resolver = "2"

[workspace.dependencies]
bevy = "0.14"
bevy_renet = "0.0.12"
renet = "0.0.15"
bevy_rapier3d = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"