[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_renet = { workspace = true }
renet = { workspace = true }
bevy_rapier3d = { workspace = true }
shared = { path = "../shared" }